hitonuevo/proyecto_inmuebles/gestion_inmuebles/urls.py
from django.urls import path
from . import views

app_name = 'gestion_inmuebles'

urlpatterns = [
    path('inmuebles/', views.InmuebleListView.as_view(), name='inmueble_list'),
    path('inmueble/<int:inmueble_id>/', views.InmuebleDetailView.as_view(), name='inmueble_detail'),
    path('inmueble/create/', views.InmuebleCreateView.as_view(), name='inmueble_create'),
    
]

hitonuevo/proyecto_inmuebles/proyecto_inmuebles/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestion_inmuebles.urls')), #este codigo incluye las URLS de la app
]

hitonuevo/proyecto_inmuebles/gestion_inmuebles/models.py
from django.db import models

# Create your models here.


class Usuario(models.Model):
    TIPOS_USUARIO = [
        ('Arrendador', 'Arrendador'),
        ('Arrendatario', 'Arrendatario'),
    ]

    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    rut = models.CharField(max_length=12, unique=True)
    direccion = models.CharField(max_length=255)
    telefono = models.CharField(max_length=15)
    correo_electronico = models.EmailField(unique=True)
    tipo_usuario = models.CharField(max_length=20, choices=TIPOS_USUARIO)

    def __str__(self):
        return f"{self.nombres} {self.apellidos} ({self.tipo_usuario})"


class Inmueble(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    m2_construidos = models.FloatField()
    m2_totales = models.FloatField()
    estacionamientos = models.IntegerField()
    habitaciones = models.IntegerField()
    banos = models.IntegerField()
    direccion = models.CharField(max_length=200)
    comuna = models.CharField(max_length=100)
    tipo_inmueble = models.CharField(max_length=50)
    precio_mensual = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.nombre


class RelacionUsuarioInmueble(models.Model):
    ESTADOS = [
        ('Pendiente', 'Pendiente'),
        ('Aceptada', 'Aceptada'),
        ('Rechazada', 'Rechazada'),
    ]

    usuario = models.ForeignKey(
        Usuario, on_delete=models.CASCADE, related_name='relaciones')
    inmueble = models.ForeignKey(
        Inmueble, on_delete=models.CASCADE, related_name='relaciones')
    estado = models.CharField(
        max_length=20, choices=ESTADOS, default='Pendiente')
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.usuario} - {self.inmueble} ({self.estado})"

hitonuevo/proyecto_inmuebles/gestion_inmuebles/forms.py
from django import forms
from .models import Inmueble, Usuario

class InmuebleForm(forms.ModelForm): #este es el formulario para crear el inmueble
    class Meta:
        model = Inmueble
        fields = ['nombre', 'descripcion', 'm2_construidos', 'm2_totales', 'estacionamientos',
                  'habitaciones', 'banos', 'direccion', 'comuna', 'tipo_inmueble', 'precio_mensual']
        
class UsuarioForm(forms.ModelForm): #este es el formulario para registrar un usuario
    class Meta:
        model = Usuario
        fields = ['nombres', 'apellidos', 'rut', 'direccion', 'telefono', 'correo_electronico', 'tipo_usuario']

        

hitonuevo/proyecto_inmuebles/gestion_inmuebles/views.py
from django.shortcuts import render, get_list_or_404, redirect
from gestion_inmuebles.models import Usuario, Inmueble, RelacionUsuarioInmueble
from .models import Inmueble
from django.views import View
from .forms import InmuebleForm
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy


# Create your views here.


def listar_inmuebles(request):
    inmuebles = Inmueble.objects.all()
    return render(request, 'listar_inmuebles.html', {'inmuebles': inmuebles})


def crear_usuario(request):
    if request.method == 'POST':
        nombres = request.POST.get('nombres')
        apellidos = request.POST.get('apellidos')
        rut = request.POST.get('rut')
        direccion = request.POST.get('direccion')
        telefono = request.POST.get('telefono')
        correo = request.POST.get('correo_electronico')
        tipo_usuario = request.POST.get('tipo_usuario')

        nuevo_usuario = Usuario.objects.create(
            nombres=nombres,
            apellidos=apellidos,
            rut=rut,
            direccion=direccion,
            telefono=telefono,
            correo_electronico=correo,
            tipo_usuario=tipo_usuario
        )
        return render(request, 'usuario_creado.html', {'usuario': nuevo_usuario})

class InmuebleListView(View): #esta vista es para listar los inmuebles
    def get(self, request):
        inmuebles = Inmueble.objects.all()
        return render(request, 'gestion_inmuebles/inmueble_list.html', {'inmuebles': inmuebles})
    
class InmuebleDetailView(View): #esta vista es para mostrar los detalles de los inmuebles
    def get(self, request, inmueble_id):
        inmueble = get_list_or_404(Inmueble, pk=inmueble_id)
        return render(request, 'gestion_inmuebles/inmueble_detail.html', {'inmueble':inmueble})
    
class InmuebleCreateView(CreateView):  # Esta vista es para crear un inmueble, solo para arrendadores
    model = Inmueble
    form_class = InmuebleForm
    template_name = 'gestion_inmuebles/inmueble_form.html'
    success_url = reverse_lazy('gestion_inmuebles:inmueble_list')   # Redirige a la lista de inmuebles

    def form_valid(self, form):
        # Aquí puedes agregar lógica adicional si es necesario
        return super().form_valid(form)

hitonuevo/proyecto_inmuebles/gestion_inmuebles/templates/gestion_inmuebles/inmueble_detail.html
#detalles de los inmuebles

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles del inmueble</title>
</head>
<body>
    <h1> {{inmueble.nombre}} </h1>
    <p> {{inmueble.descripcion}} </p>
    <p> Direccion: {{inmueble.direccion}} </p>
    <p> Comuna: {{inmueble.comuna}} </p>
    <p> Precio Mensual: $ {{inmueble.precio_mensual}} </p>
    <p> Área Construida: {{inmueble.m2_construidos}} m2 </p>
    <p> Área Total: {{inmueble.m2_totales}} m2 </p>
    <p> Habitaciones: {{inmueble.habitaciones}} </p>
    <p> Baños: {{inmueble.banos}} </p>
    <p> Estacionamientos: {{inmueble.estacionamientos}} </p>
    
</body>
</html>

hitonuevo/proyecto_inmuebles/gestion_inmuebles/templates/gestion_inmuebles/inmueble_form.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Inmueble</title>
</head>
<body>
    <h1>Crear un nuevo inmueble</h1>
    <form method="POST">
        {% csrf_token %}
        
        <!-- Mostrar errores generales si los hay -->
        {% if form.errors %}
            <div class="error">
                <p>Hubo errores en el formulario, por favor revisa los campos.</p>
            </div>
        {% endif %}
        
        <!-- Iterar sobre cada campo del formulario -->
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label> <!-- Etiqueta del campo -->
                {{ field }} <!-- El campo del formulario -->
                
                <!-- Si hay errores para este campo, mostrarlos -->
                {% if field.errors %}
                    <ul class="error-list">
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>
        {% endfor %}
        
        <button type="submit">Crear Inmueble</button>
    </form>
</body>
</html>

hitonuevo/proyecto_inmuebles/gestion_inmuebles/templates/gestion_inmuebles/inmueble_list.html
#pagina de listado de inmuebles

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inmuebles Disponibles</title>
</head>
<body>
    <h1>Lista de inmuebles</h1>
    <ul>
        {% for inmueble in inmuebles %}
            <li>
                <a href="{% url 'gestion_inmuebles:inmueble_detail' inmueble.id %}"> {{ inmueble.nombre }} </a>
            </li>
        {% endfor %}
    </ul>
    
</body>
</html>